joystick_relay:
  ros__parameters:
    priority: True
    turbo:
      linear_forward_min: 0.2 #min vel when we descrease the velocity in the mux
      linear_forward_max: 0.7 #max vel when we descrease the velocity in the mux
      linear_backward_min: 0.2 #min vel when we descrease the velocity in the mux
      linear_backward_max: 0.7 #max vel when we descrease the velocity in the mux
      angular_min: 0.7
      angular_max: 5.0
      steps: 3      
